import type { Component } from 'vue';
import {
    AlarmClock,
    Apple,
    Atom,
    BadgeCheck,
    Barcode,
    Bookmark,
    Brain,
    BriefcaseBusiness,
    CalendarCheck,
    CalendarDays,
    ChartBar,
    CircleDollarSign,
    ClipboardList,
    Cloud,
    Code,
    Coffee,
    Dumbbell,
    FileText,
    Flame,
    Flower2,
    Gamepad2,
    Globe,
    GraduationCap,
    Heart,
    Home,
    Inbox,
    Layers,
    Lightbulb,
    ListChecks,
    Mail,
    Map,
    MessageSquare,
    Music,
    NotebookPen,
    PenTool,
    Rocket,
    Rss,
    ShoppingCart,
    Sparkles,
    SquareCheckBig,
    Star,
    Sun,
    Target,
    Trophy,
    Users,
    Wrench,
    Zap,
} from 'lucide-vue-next';
import type { BlockType, RoutineBlock } from '@/types';

export const ICON_MAP: Record<string, Component> = {
    AlarmClock,
    Apple,
    Atom,
    BadgeCheck,
    Barcode,
    Bookmark,
    Brain,
    BriefcaseBusiness,
    CalendarCheck,
    CalendarDays,
    ChartBar,
    CircleDollarSign,
    ClipboardList,
    Cloud,
    Code,
    Coffee,
    Dumbbell,
    FileText,
    Flame,
    Flower2,
    Gamepad2,
    Globe,
    GraduationCap,
    Heart,
    Home,
    Inbox,
    Layers,
    Lightbulb,
    ListChecks,
    Mail,
    Map,
    MessageSquare,
    Music,
    NotebookPen,
    PenTool,
    Rocket,
    Rss,
    ShoppingCart,
    Sparkles,
    SquareCheckBig,
    Star,
    Sun,
    Target,
    Trophy,
    Users,
    Wrench,
    Zap,
};

export const DEFAULT_BLOCK_ICONS: Record<BlockType, string> = {
    clickup: 'SquareCheckBig',
    braindump: 'Brain',
    habits: 'ListChecks',
    feed: 'Rss',
    notes: 'NotebookPen',
    plan: 'CalendarCheck',
    custom: 'Wrench',
};

export function getDefaultIconName(type: BlockType): string {
    return DEFAULT_BLOCK_ICONS[type] ?? 'Wrench';
}

export function resolveBlockIcon(block: RoutineBlock): Component {
    const iconName = (block.config?.icon as string) || DEFAULT_BLOCK_ICONS[block.type] || 'Wrench';
    return ICON_MAP[iconName] ?? ICON_MAP.Wrench;
}

export const AVAILABLE_ICONS = Object.entries(ICON_MAP).map(([name, component]) => ({
    name,
    component,
}));
